# Generated by Django 3.1.3 on 2021-07-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid19',
        ),
    ]
